name: Retail Pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - main

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  retail-pipeline:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Project Structure
        run: |
          pwd
          ls -R

      - name: Run Bronze Layer
        run: |
          python -m src.bronze.ingest_data

      - name: Verify Bronze Output
        run: |
          find bronze -type d || true

      - name: Run Silver Layer
        run: |
          python -m src.silver.transform_data

      - name: Verify Silver Output
        run: |
          find silver -type d || true

      - name: Run Gold Layer
        run: |
          python -m src.gold.build_marts

      - name: Verify Gold Output
        run: |
          find gold -type f || true

      - name: Upload Gold File To Azure Blob
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          python scripts/upload_blob.py